-- ============================================================
-- 113: idx_commentary_fts_legal rebuild — corpus-backlog flip-prep adds 7 served slugs
-- ============================================================
-- WHY. Corpus-backlog decision 5 (2026-08-13) unparked the v2 staged commentaries:
-- barnes-crosswire-nt, scofield-crosswire, pnt-crosswire and poole-tcp were
-- re-ingested from their named editions (license verified before decode;
-- docs/evidence/resourcing/batch-summary-2026-08-13.md) and joined
-- SERVED_PROSE_WORKS; whitefield-works (volume-parameterized profile,
-- docs/evidence/profiles/whitefield-2026-08-13T04-26-42Z.log) joined
-- SERVED_SERMON_WORKS; donne-divine-poems and herrick-noble-numbers
-- (section-scoped profiles, docs/evidence/profiles/donne-herrick-20260813T043613Z.log)
-- joined SERVED_SONG_VERSE_WORKS. All seven flow into
-- LEGAL_COMMENTARY_ENTRIES_PREDICATE's `work IN (...)` leg — and this index's
-- predicate must stay byte-identical to that constant
-- (018_register_partial_indexes.sql:4-6, guarded by
-- web/test/invariants/fts-legal-index-sync.test.ts, which caught the drift).
--
-- FUNCTIONAL DELTA: indexability only. The seven works' commentary_entries rows
-- are written by the parent's corpus-copy with clean named-edition source_urls
-- (crosswire.org / github.com/textcreationpartnership / gutenberg.org — none on
-- the forbidden-provenance denylist), so the new predicate admits exactly them
-- and nothing else. The lane/verse registers are unaffected at query time:
-- EXEGETICAL_FTS_EXCLUSION still excludes sermon + hymn/poetry works from the
-- exegetical FTS surface (same note as 037's header).
--
-- The predicate below was GENERATED BY PRINTING the constant
-- (`npx tsx -e "import { LEGAL_COMMENTARY_ENTRIES_PREDICATE } ..."`), never
-- hand-edited from the old text — the 108 discipline.
--
-- ZERO-WINDOW, the 037/108 pattern: build the replacement under a NEW name with
-- the SAME opclass and the new predicate, let it go VALID, drop the old serving
-- index, then rename. A usable index exists at every instant.
--
-- CONCURRENTLY: run via `db/apply-migration-concurrent.mjs` (splits on
-- --SPLIT--). Each statement runs in its OWN implicit transaction — neither
-- CREATE INDEX CONCURRENTLY nor DROP INDEX CONCURRENTLY may run inside a txn
-- block. Run as neondb_owner.
--
-- Rollback: reversible by the same pattern in the other direction (rebuild with
--   the 108 predicate). The destructive step is the DROP, and it only ever runs
--   after the replacement is VALID.
--   Emergency: DROP INDEX CONCURRENTLY IF EXISTS idx_commentary_fts_legal_v9;
-- ============================================================
-- Byte-identical to LEGAL_COMMENTARY_ENTRIES_PREDICATE as of 2026-08-13 (the 108
-- predicate plus the seven flip-prep slugs; author legs and the provenance
-- condition carried forward verbatim). 108 built _v8; this builds _v9 and
-- renames it into the serving name.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_commentary_fts_legal_v9
  ON commentary_entries USING GIN (tsv)
  WHERE ((author IN ('John Gill','Jamieson, Fausset & Brown','Adam Clarke','Matthew Henry','Barnes'' Notes','Albert Barnes','John Wesley','John Calvin')
   OR (author = 'John Chrysostom' AND book IN (40, 43, 44))
   OR (author = 'Augustine of Hippo' AND book IN (19, 43))
   OR work IN ('keil-delitzsch','catena-aurea','chrysostom-homilies','augustine-homilies','barnes-crosswire-nt','scofield-crosswire','pnt-crosswire','poole-tcp','olney-hymns','scottish-psalter-1650','neale-eastern-hymns','watts-hymns','watts-psalms','keble-christian-year','herbert-temple','montgomery-sacred-poems','rossetti-verses','traherne-poems','milton-poetical-works','hopkins-poems','tennyson-in-memoriam','dante-divine-comedy','wheatley-poems','donne-divine-poems','herrick-noble-numbers','spurgeon-sermons','maclaren-expositions','watson-works','flavel-works','edwards-works','wesley-sermons','whitefield-works','owen-works','hodge-systematic','calvin-institutes','schaff-creeds'))
  AND (source_url IS NULL OR (source_url NOT ILIKE '%biblehub.com%' AND source_url NOT ILIKE '%studylight.org%' AND source_url NOT ILIKE '%historicalchristian.faith%')));
--SPLIT--
DROP INDEX CONCURRENTLY IF EXISTS idx_commentary_fts_legal;
--SPLIT--
ALTER INDEX idx_commentary_fts_legal_v9 RENAME TO idx_commentary_fts_legal;
