-- ============================================================
-- 115: idx_commentary_fts_legal rebuild — gill-song rejoins the predicate after the fork merge
-- ============================================================
-- WHY. Two branches forked from 6cbbbd6 (2026-08-11) and each grew the serving
-- lists independently: the corpus-backlog lane added seven works and rebuilt this
-- index (113, applied dev+prod 2026-08-14) from ITS routing.ts — which did not
-- contain `gill-song`, added on the other branch 2026-08-12 (509d690, owner
-- ruling "Song of Solomon, fix it", migration 109, deployed and serving). So from
-- the moment 113 applied, gill-song's commentary_entries rows fell OUT of the
-- partial FTS index: vector retrieval still reaches them, keyword/FTS does not.
-- The merge (feat/corpus-cdn, 2026-08-15) put both lists in one routing.ts and
-- BOTH lockstep guards went red — fts-legal-index-sync (predicate drift) and
-- legal-hnsw-index-sync (served slug missing from newest FTS migration). This
-- migration is the rebuild those tests demand: 113's predicate + gill-song.
--
-- FUNCTIONAL DELTA: indexability only, one work. gill-song's rows carry clean
-- provenance (ingested 2026-08-12 from a named PD edition; the forbidden-
-- provenance tail of the predicate is unchanged), so the new predicate admits
-- exactly the union the merged routing serves and nothing else.
--
-- The predicate below was GENERATED BY PRINTING the constant
-- (`npx tsx -e "import { LEGAL_COMMENTARY_ENTRIES_PREDICATE } from './web/src/lib/legal-corpus'; console.log(...)"`),
-- never hand-edited from the old text — the 108 discipline.
--
-- ZERO-WINDOW, the 037/108/113 pattern: build the replacement under a NEW name
-- with the SAME opclass and the new predicate, let it go VALID, drop the old
-- serving index, then rename. A usable index exists at every instant.
--
-- CONCURRENTLY: run via `db/apply-migration-concurrent.mjs` (splits on
-- --SPLIT--). Each statement runs in its OWN implicit transaction — neither
-- CREATE INDEX CONCURRENTLY nor DROP INDEX CONCURRENTLY may run inside a txn
-- block. Run as neondb_owner.
--
-- Rollback: reversible by the same pattern in the other direction (rebuild with
-- the 113 predicate). The destructive step is the DROP, and it only ever runs
-- after the replacement index is valid.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_commentary_fts_legal_v10
  ON commentary_entries USING GIN (tsv)
  WHERE ((author IN ('John Gill','Jamieson, Fausset & Brown','Adam Clarke','Matthew Henry','Barnes'' Notes','Albert Barnes','John Wesley','John Calvin')
   OR (author = 'John Chrysostom' AND book IN (40, 43, 44))
   OR (author = 'Augustine of Hippo' AND book IN (19, 43))
   OR work IN ('keil-delitzsch','catena-aurea','chrysostom-homilies','augustine-homilies','barnes-crosswire-nt','scofield-crosswire','pnt-crosswire','poole-tcp','gill-song','olney-hymns','scottish-psalter-1650','neale-eastern-hymns','watts-hymns','watts-psalms','keble-christian-year','herbert-temple','montgomery-sacred-poems','rossetti-verses','traherne-poems','milton-poetical-works','hopkins-poems','tennyson-in-memoriam','dante-divine-comedy','wheatley-poems','donne-divine-poems','herrick-noble-numbers','spurgeon-sermons','maclaren-expositions','watson-works','flavel-works','edwards-works','wesley-sermons','whitefield-works','owen-works','hodge-systematic','calvin-institutes','schaff-creeds'))
  AND (source_url IS NULL OR (source_url NOT ILIKE '%biblehub.com%' AND source_url NOT ILIKE '%studylight.org%' AND source_url NOT ILIKE '%historicalchristian.faith%')));
--SPLIT--
DROP INDEX CONCURRENTLY IF EXISTS idx_commentary_fts_legal;
--SPLIT--
ALTER INDEX idx_commentary_fts_legal_v10 RENAME TO idx_commentary_fts_legal;
