-- ============================================================
-- 118: idx_commentary_fts_legal rebuild — Pseudo-Origen joins the MUST_NOT_SERVE veto
-- ============================================================
-- WHY. Owner ruling 2026-08-18: the standing Origen veto (A6 2026-07-17) extends to the
-- pseudonymous attribution. 117 left `Pseudo-Origen  (as quoted by Aquinas, AD 1274)` (12 rows on
-- prod) passing the veto — not a listed name, and neither the first-token nor the name-prefix rule
-- reaches it — so it was still excluded only by absence from the allowlist, the weak mechanism this
-- whole line of work exists to replace.
--
-- NARROW ON PURPOSE. commentary_entries carries TWENTY-THREE `Pseudo-` author strings, ~660 rows
-- (Pseudo-Chrysostom 370, Pseudo-Jerome 198, Pseudo-Clement 173, Pseudo-Augustine 29,
-- Pseudo-Athanasius 28, …). `Pseudo-X` means "wrongly attributed to X": the text is by someone
-- else, usually anonymous and ancient. A blanket `Pseudo-%` rule would veto twenty-two authors on
-- the strength of a name that is not theirs and against whom no ruling exists. Only Origen's is
-- added, because only Origen has the ruling.
--
-- FUNCTIONAL DELTA: NONE. The 12 rows were already refused by the allowlist; this moves them from
-- "excluded because unnamed" to "excluded because named and refused". Verified after apply.
--
-- Predicate GENERATED BY PRINTING the constant (the 108 discipline), never hand-edited.
-- ZERO-WINDOW, the 037/108/113/115/117 pattern. Run via db/apply-migration-concurrent.mjs.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_commentary_fts_legal_v12
  ON commentary_entries USING GIN (tsv)
  WHERE ((author IN ('John Gill','Jamieson, Fausset & Brown','Adam Clarke','Matthew Henry','Barnes'' Notes','Albert Barnes','John Wesley','John Calvin')
   OR (author = 'John Chrysostom' AND book IN (40, 43, 44))
   OR (author = 'Augustine of Hippo' AND book IN (19, 43))
   OR work IN ('keil-delitzsch','catena-aurea','chrysostom-homilies','augustine-homilies','barnes-crosswire-nt','scofield-crosswire','pnt-crosswire','poole-tcp','gill-song','olney-hymns','scottish-psalter-1650','neale-eastern-hymns','watts-hymns','watts-psalms','keble-christian-year','herbert-temple','montgomery-sacred-poems','rossetti-verses','traherne-poems','milton-poetical-works','hopkins-poems','tennyson-in-memoriam','dante-divine-comedy','wheatley-poems','donne-divine-poems','herrick-noble-numbers','spurgeon-sermons','maclaren-expositions','watson-works','flavel-works','edwards-works','wesley-sermons','whitefield-works','owen-works','hodge-systematic','calvin-institutes','schaff-creeds'))
  AND (source_url IS NULL OR (source_url NOT ILIKE '%biblehub.com%' AND source_url NOT ILIKE '%studylight.org%' AND source_url NOT ILIKE '%historicalchristian.faith%'))
  AND NOT (
     author IN ('Tyndale Study Notes','Tyndale Open Study Notes','Theophylact','Bonaventure','Oecumenius','Origen','Origen of Alexandria','Aquinas-Larcher','CS Lewis','GK Chesterton','Douglas Wilson','JRR Tolkien','Pseudo-Origen')
     OR split_part(author, ' of ', 1) IN ('Tyndale Study Notes','Tyndale Open Study Notes','Theophylact','Bonaventure','Oecumenius','Origen','Origen of Alexandria','Aquinas-Larcher','CS Lewis','GK Chesterton','Douglas Wilson','JRR Tolkien','Pseudo-Origen')
     OR split_part(author, ' the ', 1) IN ('Tyndale Study Notes','Tyndale Open Study Notes','Theophylact','Bonaventure','Oecumenius','Origen','Origen of Alexandria','Aquinas-Larcher','CS Lewis','GK Chesterton','Douglas Wilson','JRR Tolkien','Pseudo-Origen')
     OR author LIKE 'Tyndale Study Notes %'
     OR author LIKE 'Tyndale Open Study Notes %'
     OR author LIKE 'Theophylact %'
     OR author LIKE 'Bonaventure %'
     OR author LIKE 'Oecumenius %'
     OR author LIKE 'Origen %'
     OR author LIKE 'Origen of Alexandria %'
     OR author LIKE 'Aquinas-Larcher %'
     OR author LIKE 'CS Lewis %'
     OR author LIKE 'GK Chesterton %'
     OR author LIKE 'Douglas Wilson %'
     OR author LIKE 'JRR Tolkien %'
     OR author LIKE 'Pseudo-Origen %'
     OR author LIKE 'Jerome''s%'
   ));
--SPLIT--
DROP INDEX CONCURRENTLY IF EXISTS idx_commentary_fts_legal;
--SPLIT--
ALTER INDEX idx_commentary_fts_legal_v12 RENAME TO idx_commentary_fts_legal;
