// Auto-generated by scripts/gen-web-empty-verses.mts — do not edit.
//
// Verse ids present in the shipped WEB asset as TEXT-LESS placeholders. WEB keeps the verse
// NUMBER for the critical-text omissions but carries no text, so a reference to one resolves to
// nothing on screen. verseExists() must reject these: `passage_exists` is named for whether a
// passage exists, and a verse with no text does not (DEEP_SWEEP D4).
export const WEB_EMPTY_VERSE_IDS: ReadonlySet<number> = new Set([42017036,44008037,44015034,44024007,45016025]);
