#!/usr/bin/env tsx
// CLI: parse WEB USFM files → static verse-counts module + verse JSON for the reader.
//
// Usage:  pnpm ingest:web
//         tsx src/ingest/ingest-web.ts [usfm-dir]
//
// Defaults to data/raw/web-usfm/ in the repo root.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseUsfmDir, computeVerseCounts, type ParsedVerse } from './usfm';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..', '..');
const usfmDir = process.argv[2] ?? join(root, 'data', 'raw', 'web-usfm');

console.log(`Parsing USFM from ${usfmDir}…`);
const verses = parseUsfmDir(usfmDir);
console.log(`  ${verses.length} verse rows parsed`);

const counts = computeVerseCounts(verses);
const bookCount = Object.keys(counts).length;
const chapterCount = Object.values(counts).reduce(
  (sum, ch) => sum + Object.keys(ch).length,
  0,
);
console.log(`  ${bookCount} books, ${chapterCount} chapters`);

// 1. Static verse-counts module (used by ref-parse VerseCountProvider on client)
const countsPath = join(root, 'src', 'bible', 'verse-counts.ts');
const countsModule = `// Auto-generated by ingest-web.ts — do not edit.
// Verse counts per chapter for the WEB (KJV versification).

import type { VerseCountProvider } from './ref-parse';

const COUNTS: Record<number, Record<number, number>> = ${JSON.stringify(counts)};

export const webVerseCounts: VerseCountProvider = {
  verseCount(bookNum: number, chapter: number): number | undefined {
    return COUNTS[bookNum]?.[chapter];
  },
};

export { COUNTS as RAW_VERSE_COUNTS };
`;
writeFileSync(countsPath, countsModule);
console.log(`  Wrote ${countsPath}`);

// 2. Verse JSON grouped by book/chapter for the reader.
// Structure: data/web/{bookSlug}/{chapter}.json = { verses: [{verse, text}] }
import { BOOKS } from '../bible/books';

const slugByNum = new Map(BOOKS.map((b) => [b.bookNum, b.slug]));
const webDataDir = join(root, 'data', 'web');

const byBookChapter = new Map<string, ParsedVerse[]>();
for (const v of verses) {
  const key = `${v.book}:${v.chapter}`;
  const arr = byBookChapter.get(key);
  if (arr) arr.push(v);
  else byBookChapter.set(key, [v]);
}

let fileCount = 0;
for (const [key, chVerses] of byBookChapter) {
  const [bookStr, chapStr] = key.split(':');
  const slug = slugByNum.get(Number(bookStr));
  if (!slug) continue;
  const dir = join(webDataDir, slug);
  mkdirSync(dir, { recursive: true });
  const payload = {
    book: Number(bookStr),
    chapter: Number(chapStr),
    verses: chVerses.map((v) => ({ verse: v.verse, text: v.text })),
  };
  writeFileSync(join(dir, `${chapStr}.json`), JSON.stringify(payload));
  fileCount++;
}
console.log(`  Wrote ${fileCount} chapter JSON files to ${webDataDir}`);

// 3. Validate: every book in BOOKS has data, every chapter is covered
let missingBooks = 0;
let missingChapters = 0;
for (const book of BOOKS) {
  const bc = counts[book.bookNum];
  if (!bc) {
    console.warn(`  ⚠ Missing book: ${book.name} (#${book.bookNum})`);
    missingBooks++;
    continue;
  }
  for (let c = 1; c <= book.chapterCount; c++) {
    if (bc[c] === undefined) {
      console.warn(`  ⚠ Missing chapter: ${book.name} ${c}`);
      missingChapters++;
    }
  }
}
if (missingBooks === 0 && missingChapters === 0) {
  console.log('  ✓ All 66 books, all chapters present');
} else {
  console.warn(`  ${missingBooks} missing books, ${missingChapters} missing chapters`);
}

console.log('Done.');
