// Book alias table for the interactive reference resolver.
//
// Aliases are stored normalized: lowercase, no periods, single spaces,
// digit ordinals ("1 john", never "I John" — the normalizer maps roman and
// word ordinals to digits before lookup). The book's name and slug are
// implicit aliases; entries here are the additional conventional forms
// (SBL / Logos / BibleGateway abbreviation sets).
//
// Convention beats prefix logic: where a short form is conventionally
// bound to one book ("phil" → Philippians, "jud" → Jude), it is listed
// explicitly so prefix ambiguity can never steal it.

export const BOOK_ALIASES: Record<string, string[]> = {
  gen: ['genesis', 'gn', 'ge'],
  exo: ['exodus', 'ex', 'exod'],
  lev: ['leviticus', 'lv'],
  num: ['numbers', 'nm', 'nu', 'numb'],
  deu: ['deuteronomy', 'dt', 'deut'],
  jos: ['joshua', 'josh', 'jsh'],
  jdg: ['judges', 'judg', 'jgs', 'jdgs'],
  rut: ['ruth', 'ru', 'rth'],
  '1sa': ['1 samuel', '1 sam', '1 sm', '1 sa'],
  '2sa': ['2 samuel', '2 sam', '2 sm', '2 sa'],
  '1ki': ['1 kings', '1 kgs', '1 kin', '1 ki'],
  '2ki': ['2 kings', '2 kgs', '2 kin', '2 ki'],
  '1ch': ['1 chronicles', '1 chron', '1 chr', '1 ch'],
  '2ch': ['2 chronicles', '2 chron', '2 chr', '2 ch'],
  ezr: ['ezra'],
  neh: ['nehemiah', 'ne'],
  est: ['esther', 'esth'],
  job: ['jb'],
  psa: ['psalms', 'psalm', 'ps', 'pss', 'psm'],
  pro: ['proverbs', 'prov', 'prv', 'pr'],
  ecc: ['ecclesiastes', 'eccl', 'eccles', 'ec'],
  sng: ['song of songs', 'song of solomon', 'song', 'sos', 'canticles', 'cant'],
  isa: ['isaiah', 'is'],
  jer: ['jeremiah', 'jr'],
  lam: ['lamentations', 'lm'],
  ezk: ['ezekiel', 'ezek', 'eze'],
  dan: ['daniel', 'dn', 'dnl'],
  hos: ['hosea', 'ho'],
  jol: ['joel', 'jl'],
  amo: ['amos', 'am'],
  oba: ['obadiah', 'obad', 'ob'],
  jon: ['jonah', 'jnh'],
  mic: ['micah', 'mc'],
  nam: ['nahum', 'nah', 'na'],
  hab: ['habakkuk', 'habak'],
  zep: ['zephaniah', 'zeph', 'zp'],
  hag: ['haggai', 'hg'],
  zec: ['zechariah', 'zech', 'zc'],
  mal: ['malachi', 'ml'],
  mat: ['matthew', 'matt', 'mt'],
  mrk: ['mark', 'mk', 'mr'],
  luk: ['luke', 'lk', 'lu'],
  jhn: ['john', 'jn', 'joh'],
  act: ['acts', 'ac'],
  rom: ['romans', 'ro', 'rm'],
  '1co': ['1 corinthians', '1 cor', '1 co'],
  '2co': ['2 corinthians', '2 cor', '2 co'],
  gal: ['galatians', 'ga', 'gl'],
  eph: ['ephesians', 'ep'],
  php: ['philippians', 'phil', 'philip', 'philipp'],
  col: ['colossians', 'cl'],
  '1th': ['1 thessalonians', '1 thess', '1 thes', '1 th'],
  '2th': ['2 thessalonians', '2 thess', '2 thes', '2 th'],
  '1ti': ['1 timothy', '1 tim', '1 ti'],
  '2ti': ['2 timothy', '2 tim', '2 ti'],
  tit: ['titus'],
  phm: ['philemon', 'philem', 'phlm', 'phlmn'],
  heb: ['hebrews', 'hebr'],
  jas: ['james', 'jam', 'jms'],
  '1pe': ['1 peter', '1 pet', '1 pt', '1 pe'],
  '2pe': ['2 peter', '2 pet', '2 pt', '2 pe'],
  '1jn': ['1 john', '1 jn', '1 jhn', '1 joh'],
  '2jn': ['2 john', '2 jn', '2 jhn', '2 joh'],
  '3jn': ['3 john', '3 jn', '3 jhn', '3 joh'],
  jud: ['jude'],
  rev: ['revelation', 'revelations', 'rv', 'apoc', 'apocalypse'],
};
