#!/usr/bin/env node
/**
 * CCEL ACQUISITION SURVEY — enumerate an author's works and PROVE each one is ingestable
 * before anybody writes a manifest entry for it.
 *
 *   node scripts/ccel-survey.mjs --authors=calvin,owen,luther [--out=docs/evidence/ccel-survey.json]
 *
 * WHY THIS EXISTS. Two works quarantined on 2026-08-02 for reasons no amount of retrying would
 * fix, and both were knowable in advance:
 *
 *   vincent-word-studies   CCEL has no such work under any id. The manifest asserted one.
 *   spurgeon-treasury      CCEL has it as SCANNED PAGE IMAGES. Six volumes enumerated, parsed to
 *                          zero sections, because there is no text in them to parse.
 *
 * A manifest entry is a CLAIM that a work exists and can be read. Writing ten of them from memory
 * and discovering afterwards which were true is how an evening disappears. So this asks CCEL
 * three questions per id and records the answers:
 *
 *   1. does it resolve at all?                        (404 ⇒ the id is wrong)
 *   2. is it TEXT, or page images?                    (scans ⇒ nothing to extract)
 *   3. does it carry the div structure the adapter parses, and roughly how much?
 *
 * It writes nothing to any database and adds nothing to the manifest. Its output is a candidate
 * list for a human to accept or reject — because "this work exists and is machine-readable" is a
 * fact this can establish, while "this work belongs in the corpus" is a judgement it cannot.
 */
import fs from 'node:fs';
import path from 'node:path';
import { enumerateCcelAuthor } from '../src/ingest/adapter-ccel.ts';

const arg = (f) => process.argv.find((a) => a.startsWith(`${f}=`))?.slice(f.length + 1);
const authors = (arg('--authors') ?? '').split(',').map((s) => s.trim()).filter(Boolean);
const outPath = arg('--out') ?? 'docs/evidence/ccel-survey.json';
const capPerAuthor = Number(arg('--cap') ?? 200);
if (authors.length === 0) {
  console.error('usage: node scripts/ccel-survey.mjs --authors=a,b,c [--out=path] [--cap=N]');
  process.exit(2);
}

/** Ask CCEL what a work actually is. Never throws: an unreachable id is a finding, not a crash. */
async function inspect(id) {
  try {
    const r = await fetch(`https://www.ccel.org/ccel/${id}.xml`, { signal: AbortSignal.timeout(30_000) });
    if (!r.ok) return { id, ok: false, verdict: 'missing', detail: `HTTP ${r.status}` };
    const b = await r.text();
    const title = /<title[^>]*>([^<]{0,80})/i.exec(b)?.[1]?.trim() ?? null;
    const divs = (b.match(/<div[123]\b/g) ?? []).length;
    const pageImages = (b.match(/<img alt="Image of page/g) ?? []).length;
    const scripRefs = (b.match(/<scripRef\b/g) ?? []).length;
    // A work is SCANS when its pages are images rather than text. The ratio matters, not the
    // presence: a text work may legitimately carry a few plates.
    if (pageImages > 20 && divs > 0 && b.length / pageImages < 8_000) {
      return { id, ok: false, verdict: 'page-scans', detail: `${pageImages} page images`, title, bytes: b.length };
    }
    // "Work info:" landing pages resolve 200 and carry no structure at all.
    if (divs === 0) return { id, ok: false, verdict: 'no-structure', detail: 'no div1/2/3', title, bytes: b.length };
    if (b.length < 20_000) return { id, ok: false, verdict: 'too-small', detail: `${b.length}B`, title, bytes: b.length };
    return { id, ok: true, verdict: 'ingestable', title, bytes: b.length, divs, scripRefs };
  } catch (e) {
    return { id, ok: false, verdict: 'error', detail: String(e.message).slice(0, 60) };
  }
}

const results = [];
for (const author of authors) {
  const ids = await enumerateCcelAuthor(author, capPerAuthor);
  console.log(`\n${author} — ${ids.length} enumerated`);
  for (const id of ids) {
    const r = await inspect(id);
    results.push({ author, ...r });
    const mark = r.ok ? '\x1b[32m✓\x1b[0m' : '\x1b[90m·\x1b[0m';
    const size = r.bytes ? `${(r.bytes / 1024).toFixed(0)}KB`.padStart(8) : '        ';
    console.log(`  ${mark} ${size} ${String(r.verdict).padEnd(13)} ${r.id.padEnd(30)} ${(r.title ?? '').slice(0, 48)}`);
  }
}

const ingestable = results.filter((r) => r.ok);
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${JSON.stringify({
  _: 'CCEL acquisition survey. GENERATED by scripts/ccel-survey.mjs. Candidates for manifest entries — NOT a decision that any of them belongs in the corpus.',
  surveyedAuthors: authors,
  totals: { enumerated: results.length, ingestable: ingestable.length },
  byVerdict: results.reduce((m, r) => ({ ...m, [r.verdict]: (m[r.verdict] ?? 0) + 1 }), {}),
  results,
}, null, 2)}\n`);

console.log(`\n${ingestable.length} of ${results.length} look ingestable`);
const byVerdict = results.reduce((m, r) => ({ ...m, [r.verdict]: (m[r.verdict] ?? 0) + 1 }), {});
for (const [v, n] of Object.entries(byVerdict).sort((a, b) => b[1] - a[1])) console.log(`  ${String(v).padEnd(14)} ${n}`);
console.log(`\nwrote ${outPath}`);
