// Generates bible/empty-verses.ts from the shipped WEB asset.
//
// D4 (DEEP_SWEEP): `verseExists` in the teacher's CorpusLookup checks a verse NUMBER against
// webVerseCounts, and that table was generated by counting entries in the WEB JSON — which keeps
// TEXT-LESS PLACEHOLDERS for the critical-text omissions (Acts 8:37, 15:34, 24:7, Luke 17:36,
// Rom 16:25). So `passage_exists` — the verifier check named for whether a passage exists —
// returned true for a reference that resolves to nothing, and the reader got a dead link.
//
// Derived from the asset, never hand-maintained: an expected set typed by the same hand that
// typed the thing it guards is not a second opinion (the repo's own watchlist). Re-run this when
// the WEB asset changes, the same way verse-counts.ts is regenerated.
//
//   npx tsx scripts/gen-web-empty-verses.mts
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BOOKS } from '../src/bible/books.js';

const ASSET = 'web/public/bible/web';
const bySlug = new Map(BOOKS.map((b) => [b.slug, b.bookNum]));

const empty: number[] = [];
for (const f of readdirSync(ASSET).filter((x) => x.endsWith('.json')).sort()) {
  const slug = f.replace(/\.json$/, '');
  const bookNum = bySlug.get(slug);
  if (bookNum === undefined) continue;
  const j = JSON.parse(readFileSync(join(ASSET, f), 'utf8')) as {
    chapters?: Record<string, Array<{ verse?: number; text?: string }>>;
  };
  for (const [ch, verses] of Object.entries(j.chapters ?? {})) {
    for (const v of verses) {
      if (typeof v.verse !== 'number') continue;
      if ((v.text ?? '').trim() !== '') continue;
      empty.push(bookNum * 1_000_000 + Number(ch) * 1_000 + v.verse);
    }
  }
}
empty.sort((a, b) => a - b);

const body = `// Auto-generated by scripts/gen-web-empty-verses.mts — do not edit.
//
// Verse ids present in the shipped WEB asset as TEXT-LESS placeholders. WEB keeps the verse
// NUMBER for the critical-text omissions but carries no text, so a reference to one resolves to
// nothing on screen. verseExists() must reject these: \`passage_exists\` is named for whether a
// passage exists, and a verse with no text does not (DEEP_SWEEP D4).
export const WEB_EMPTY_VERSE_IDS: ReadonlySet<number> = new Set(${JSON.stringify(empty)});
`;
for (const out of ['src/bible/empty-verses.ts', 'web/src/bible/empty-verses.ts']) {
  writeFileSync(out, body);
}
console.log(`wrote ${empty.length} empty verse ids:`, empty.join(', '));
