// D4 half A (DEEP_SWEEP) — `passage_exists` was named for a property it did not enforce.
//
// verseExists checked a verse NUMBER against webVerseCounts, and that table was generated by
// counting entries in the shipped WEB JSON — which keeps TEXT-LESS PLACEHOLDERS for the
// critical-text omissions. So the verifier approved a Scripture reference that resolves to
// nothing: ask-client renders the passages block as reference links, and the reader then skips
// the verse entirely (verse-display.tsx: `if (!v.text) return null`). A silently dead reference,
// approved by the one check whose whole job is existence.
//
// Blast radius is exactly five verses repo-wide, derived from the asset rather than listed by
// hand (scripts/gen-web-empty-verses.mts): Luke 17:36, Acts 8:37, Acts 15:34, Acts 24:7,
// Romans 16:25.
//
// Existing coverage for this property was NONE. The only passage_exists test
// (test/verifier.test.ts) runs against src/verifier/memory-corpus.ts, whose verseExists is a
// hand-maintained `missingVerses` allowlist — the SHIPPED webVerseCounts predicate was never
// exercised by anything. That is the repo's own watchlist item about expected sets typed by the
// same hand as the thing they guard.
import { describe, expect, it } from 'vitest';
import { buildCorpusLookup } from '@/lib/teacher/corpus';
import { WEB_EMPTY_VERSE_IDS } from '@bible/empty-verses';
import type { RetrievedChunk } from '@/lib/teacher/retrieve';

const lookup = buildCorpusLookup([] as RetrievedChunk[]);
const id = (b: number, c: number, v: number) => b * 1_000_000 + c * 1_000 + v;

describe('D4 — a verse with no text does not exist', () => {
  it('the derived set is the five known WEB placeholders, and is not empty', () => {
    expect([...WEB_EMPTY_VERSE_IDS].sort((a, b) => a - b)).toEqual([
      id(42, 17, 36), id(44, 8, 37), id(44, 15, 34), id(44, 24, 7), id(45, 16, 25),
    ]);
  });

  it.each([
    ['Luke 17:36', id(42, 17, 36)],
    ['Acts 8:37', id(44, 8, 37)],
    ['Acts 15:34', id(44, 15, 34)],
    ['Acts 24:7', id(44, 24, 7)],
    ['Romans 16:25', id(45, 16, 25)],
  ])('%s is a text-less placeholder and must NOT satisfy verseExists', async (_label, verseId) => {
    expect(await lookup.verseExists('web', verseId)).toBe(false);
  });

  it('ordinary verses are unaffected', async () => {
    for (const v of [id(43, 3, 16), id(45, 8, 28), id(42, 17, 35), id(44, 8, 36), id(45, 16, 24)]) {
      expect(await lookup.verseExists('web', v), String(v)).toBe(true);
    }
  });

  it('a verse number beyond the chapter is still rejected — the count check is not lost', async () => {
    expect(await lookup.verseExists('web', id(45, 16, 26))).toBe(false);
    expect(await lookup.verseExists('web', id(43, 3, 999))).toBe(false);
  });
});
