import { decodeVerseId } from '@bible/verse-id';
import { webVerseCounts } from '@bible/verse-counts';
import { WEB_EMPTY_VERSE_IDS } from '@bible/empty-verses';
import type { CorpusLookup } from '@/verifier/types';
import type { RetrievedChunk } from './retrieve';
import type { UserVoice } from './user-voices';

// Builds the verifier's CorpusLookup from a retrieval set. Sections are the
// retrieved chunks, indexed 1..N (the section_id the composer is told to cite),
// so the verifier's quote/attribution checks resolve against exactly what the
// model was shown — it cannot cite outside the retrieval set.
//
// verseExists is REAL (unlike the CLI stub): a passage verse must fall within
// the WEB versification's verse count for its book/chapter. This restores the
// verifier's passage_exists guard on the teacher path.
//
// User-library sections (Slice 4) are indexed N+1..N+M — the ids teach.ts's
// formatUserLibrarySources assigns — and keyed under the `user_library:` namespace, so
// normalize-contract stamps their true origin and the verifier's H4 trust boundary
// (additive-only) applies to them automatically. Their `source` carries author 'You' /
// tradition 'unknown' to match the sectionAttributions teach.ts builds; 'unknown' is in
// the verifier's NOT_A_TRADITION set, so a user voice can never count as a tradition.
export function buildCorpusLookup(retrieval: RetrievedChunk[], userVoices: UserVoice[] = []): CorpusLookup {
  const sections = new Map(
    retrieval.map((r, i) => {
      const id = i + 1;
      return [
        `corpus:${id}`,
        {
          id,
          body: r.content,
          origin: 'corpus' as const,
          source: {
            id,
            author: r.metadata.author,
            title: r.metadata.sourceTitle,
            tradition: r.metadata.tradition ?? 'unknown',
          },
          // The verse range this chunk is indexed to — the verifier grounds voice-block
          // anchors against it (LONG_NIGHT H2), so a fabricated cross-book anchor is rejected.
          //
          // D5 (DEEP_SWEEP): `verseEnd` arrives as 0 for a row with no anchor
          // (register-writer.ts:248 writes `a?.verseIdEnd ?? 0`), and unanchored SERVED rows
          // exist by design. v1.ts:141 tests `anchor.start <= section.verses.end`, so a section
          // with a REAL verseId and verseEnd 0 had an INVERTED range that rejected every anchor
          // as anchor_offbase — a voice that could never satisfy passages_grounded, and a
          // retrieval set full of them forced the retry loop into the fallback. routing.ts:457
          // already defends against exactly this ("verseEnd can be 0/null/invalid under data
          // drift"); this path did not. Same fallback, same reason.
          //
          // NOT extended to skip grounding when the row is FULLY unanchored (verseId 0). That
          // would fail OPEN: a fabricated anchor on an unanchored source would stop being
          // rejected. Rejection there is the correct outcome and stays.
          verses: {
            start: r.metadata.verseId,
            end:
              typeof r.metadata.verseEnd === 'number' && r.metadata.verseEnd >= r.metadata.verseId
                ? r.metadata.verseEnd
                : r.metadata.verseId,
          },
        },
      ];
    }),
  );

  const userSections = new Map(
    userVoices.map((v, j) => {
      const id = retrieval.length + j + 1;
      return [
        `user_library:${id}`,
        {
          id,
          body: v.text,
          origin: 'user_library' as const,
          source: { id, author: 'You', title: v.title, tradition: 'unknown' },
          ...(v.verses ? { verses: { start: v.verses.start, end: v.verses.end } } : {}),
        },
      ];
    }),
  );

  return {
    async getSection(sectionId, origin) {
      if (origin === 'user_library') return userSections.get(`user_library:${sectionId}`) ?? null;
      return sections.get(`${origin}:${sectionId}`) ?? null;
    },
    async getSource(sourceId) {
      const s = sections.get(`corpus:${sourceId}`);
      return s ? { id: s.id, author: s.source.author, title: s.source.title } : null;
    },
    async getTranslation(slug) {
      // WEB is the one translation licensed for teacher display today.
      if (slug === 'web') return { slug: 'web', isActive: true, licensedForDisplay: true };
      return null;
    },
    async verseExists(_slug, verseId) {
      const { book, chapter, verse } = decodeVerseId(verseId);
      const count = webVerseCounts.verseCount(book, chapter);
      if (!(count !== undefined && verse >= 1 && verse <= count)) return false;
      // D4 (DEEP_SWEEP): the count table was generated by counting ENTRIES in the WEB asset, and
      // WEB keeps text-less placeholders for the critical-text omissions. So the number check
      // alone answered true for a reference that resolves to nothing on screen — the reader's
      // verse-display skips an empty verse outright — and `passage_exists`, the check named for
      // whether a passage exists, approved it. A verse with no text does not exist.
      // Derived from the asset (scripts/gen-web-empty-verses.mts), never hand-listed.
      return !WEB_EMPTY_VERSE_IDS.has(verseId);
    },
  };
}
